### ISSUE TITLE
ServiceWorker code review

### ISSUE THREAD

**Issue by sgomes** [sgomes/blog#3]
Hey @jakearchibald!

Thank you for agreeing to take a look at my [ServiceWorker code](/sgomes/blog/blob/master/src/sw.js). I think it's doing the right thing, but I'm a complete beginner at it, and would really appreciate a stamp of "this looks about right" :)

Please feel free to add your comments in as you find the time. Thanks again! 👍

**Comment by jakearchibald** [comment]
> `'/assets/images/avatar.jpg',`

Ideally all static assets should be versioned so they can be cached forever.

> `// Delete old caches.`

Do you plan on using the caches API outside of this service worker registration? Might you be deleting other caches you're using here?

> `} else if (requestUrl.pathname === '/' || requestUrl.pathname === '/index.html') {`

Ideally you'd configure your server so `/index.html` redirects back to `/`, rather than have the same content at multiple URLs.

> `networkWithTimeoutAndUpdate(event, true);`

This second arg isn't used. Given that it does the same as a the `if` above, roll it into the same condition?

> `function cacheThenUpdate(event) {`

At the moment you're making a network request even if it's in the cache. Is that intentional?

When you dynamically cache stuff using this method, they'll all be lost if you update the service worker as the caches are purged in the activate event. Is this what you want?

What if some of these requests are `POST` rather than `GET`? Are you wanting to do the same intercepting?

Looks good generally!

**Comment by sgomes** [comment]
Thanks for the review, @jakearchibald! So many things I hadn't thought about in such a small ServiceWorker...

> Ideally all static assets should be versioned so they can be cached forever.

I considered doing this, but since I'm using GH pages + Cloudflare, I don't think I really have any way of setting cache headers to keep things around permanently :-/

> Do you plan on using the caches API outside of this service worker registration? Might you be deleting other caches you're using here?

Nope. I want to keep all caching code on the service worker, and if at any point I want to add user-driven caching (e.g. pinning a post), I'd prefer to have the code living in sw.js and just triggering it from the client.

> Ideally you'd configure your server so /index.html redirects back to /, rather than have the same content at multiple URLs.

Done, thanks for the tip!

> This second arg isn't used. Given that it does the same as a the if above, roll it into the same condition?

Good catch, thanks!

> At the moment you're making a network request even if it's in the cache. Is that intentional?

Yes, that's intentional. I want to show from cache immediately, and update for the next refresh if something's changed. Is there a way of doing that that doesn't involve pulling down the content? This is used for e.g. images inside posts (which can be large).

> When you dynamically cache stuff using this method, they'll all be lost if you update the service worker as the caches are purged in the activate event. Is this what you want?

Yes, I treat this sort of caching as a best-effort. If I ever implement pinning functionality, I'd like that to be more permanent, but here I'm just opportunistically caching articles the user has visited.

> What if some of these requests are POST rather than GET? Are you wanting to do the same intercepting?

I make sure that I'm only caching things within my origin, and those will all be GET.
